CREATE DATABASE INSECTARE
GO

USE INSECTARE
GO

CREATE TABLE CERCETATORI (
	ID INT PRIMARY KEY IDENTITY,
	NUME VARCHAR(100),
	PRENUME VARCHAR(100),
	EMAIL VARCHAR(100),
	DOB DATE,
	SALARIU FLOAT,
	FUNCTIE VARCHAR(100)
);

CREATE TABLE TIP_DE_CUTIE (
	ID INT PRIMARY KEY IDENTITY,
	MODEL VARCHAR(100),
	DESCRIERE VARCHAR(100),
	LUNGIME REAL,
	LATIME REAL,
	INALTIME REAL,
	PRODUCATOR VARCHAR(100)
);

CREATE TABLE INSECTARE (
	ID INT PRIMARY KEY IDENTITY,
	TITLU VARCHAR(100),
	DESCRIERE VARCHAR(100),
	ID_CERCETATOR INT FOREIGN KEY REFERENCES CERCETATORI(ID),
	ID_CUTIE INT FOREIGN KEY REFERENCES TIP_DE_CUTIE(ID)
);

CREATE TABLE INSECTE (
	ID INT PRIMARY KEY IDENTITY,
	NUME_COMUN VARCHAR(100),
	NUME_STIINTIFIC VARCHAR(100),
	DESCRIERE VARCHAR(100),
	E_DAUNATOARE BIT,
	E_ZBURATOARE BIT
);

CREATE TABLE INSECTARE_INSECTE (
	ID_INSECTAR INT FOREIGN KEY REFERENCES INSECTARE(ID),
	ID_INSECTA INT FOREIGN KEY REFERENCES INSECTE(ID),
	DATA_ADAUGARII DATE DEFAULT GETDATE()
);

ALTER TABLE INSECTARE_INSECTE
ADD CONSTRAINT PK_INSECTAR_INSECTE PRIMARY KEY (ID_INSECTAR, ID_INSECTA)
GO

CREATE OR ALTER PROCEDURE UPSERT_INSECTA (
	@ID_INSECTAR INT,
	@ID_INSECTA INT,
	@DATA_ADAUGARII DATE
) AS
BEGIN
	IF EXISTS (SELECT 1 FROM INSECTARE_INSECTE WHERE ID_INSECTAR = @ID_INSECTAR AND ID_INSECTA = @ID_INSECTA)
	BEGIN
		UPDATE INSECTARE_INSECTE
		SET DATA_ADAUGARII = @DATA_ADAUGARII
		WHERE ID_INSECTAR = @ID_INSECTAR AND ID_INSECTA = @ID_INSECTA
	END
	ELSE
	BEGIN
		INSERT INTO INSECTARE_INSECTE
		VALUES (@ID_INSECTAR, @ID_INSECTA, @DATA_ADAUGARII)
	END
END
GO

CREATE OR ALTER VIEW VW_LICURICI_BONDARI AS
SELECT DISTINCT C.NUME, C.PRENUME, C.EMAIL, TC.MODEL, IR.TITLU, IR.DESCRIERE
FROM INSECTARE_INSECTE II
JOIN INSECTARE IR ON IR.ID = II.ID_INSECTAR
JOIN CERCETATORI C ON C.ID = IR.ID_CERCETATOR
JOIN TIP_DE_CUTIE TC ON TC.ID = IR.ID_CUTIE
WHERE IR.ID IN (
	SELECT ID_INSECTAR FROM INSECTARE_INSECTE
	JOIN INSECTE I ON I.ID = ID_INSECTA
	WHERE I.NUME_COMUN = 'LICURICI'
	INTERSECT
	SELECT ID_INSECTAR FROM INSECTARE_INSECTE
	JOIN INSECTE I ON I.ID = ID_INSECTA
	WHERE I.NUME_COMUN = 'BONDAR'
	)
GO

INSERT INTO CERCETATORI
VALUES 
('N1', 'P1', 'E1', '2026-01-01', 1000, 'C1'),
('N2', 'P2', 'E2', '2026-01-01', 1000, 'C2'),
('N3', 'P3', 'E3', '2026-01-01', 1000, 'C3'),
('N4', 'P4', 'E4', '2026-01-01', 1000, 'C4')

SELECT * FROM CERCETATORI

INSERT INTO TIP_DE_CUTIE
VALUES
('M1', 'D1', 12.3, 4.8, 5.6, 'P1'),
('M2', 'D2', 12.3, 4.8, 5.6, 'P2'),
('M3', 'D3', 12.3, 4.8, 5.6, 'P1'),
('M4', 'D4', 12.3, 4.8, 5.6, 'P3')

SELECT * FROM TIP_DE_CUTIE

INSERT INTO INSECTARE
VALUES
('T1', 'D1', 1, 1),
('T2', 'D2', 1, 2),
('T3', 'D3', 3, 4),
('T4', 'D4', 2, 3)

SELECT * FROM INSECTARE

INSERT INTO INSECTE
VALUES
('LICURICI', 'NS1', 'D1', 0, 1),
('BONDAR', 'NS2', 'D2', 0, 1),
('LIBELULA', 'NS3', 'D3', 0, 1)

SELECT * FROM INSECTE

INSERT INTO INSECTARE_INSECTE (ID_INSECTAR, ID_INSECTA)
VALUES (1, 1), (1, 2), (2, 1), (3, 2), (4, 1), (4, 2), (4, 3)

SELECT * FROM INSECTARE_INSECTE

EXEC UPSERT_INSECTA 3, 3, '2026-01-01';
EXEC UPSERT_INSECTA 3, 3, '1998-01-01';

SELECT * FROM VW_LICURICI_BONDARI