plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot' version '4.1.0-RC1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ro.mpp2026'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation project(':Model')

    implementation 'org.springframework.boot:spring-boot-starter-web'
}

application {
    mainClass = 'JavaRestClient'
}

test {
    useJUnitPlatform()
}