-- First version
CREATE OR ALTER PROCEDURE ModifyColumnType 
AS
BEGIN
ALTER TABLE Drivers
ALTER COLUMN Salary INT;
END;

CREATE OR ALTER PROCEDURE RevertColumnChanges 
AS
BEGIN
ALTER TABLE Drivers
ALTER COLUMN Salary FLOAT;
END;

-- Second version
CREATE OR ALTER PROCEDURE AddDefaultConstraint 
AS
BEGIN
ALTER TABLE Drivers
ADD CONSTRAINT ds_df DEFAULT 10000000 FOR Salary;
END;

CREATE OR ALTER PROCEDURE RemoveDefaultConstraint 
AS
BEGIN
ALTER TABLE Drivers
DROP CONSTRAINT ds_df;
END;

-- Third version
CREATE OR ALTER PROCEDURE AddNewTable 
AS
BEGIN
CREATE TABLE Fans(
ID INT PRIMARY KEY IDENTITY(1, 1),
Name NVARCHAR(100)
)
END;

CREATE OR ALTER PROCEDURE RemoveNewTable 
AS
BEGIN
DROP TABLE Fans;
END;

-- Fourth version
CREATE OR ALTER PROCEDURE AddNewColumn 
AS
BEGIN
ALTER TABLE Fans
ADD TeamID INT;
END;

CREATE OR ALTER PROCEDURE RemoveNewColumn 
AS
BEGIN
ALTER TABLE Fans
DROP COLUMN TeamID;
END;

-- Fifth version
CREATE OR ALTER PROCEDURE AddFK 
AS
BEGIN
ALTER TABLE Fans
ADD CONSTRAINT fk_Fans_Teams FOREIGN KEY(TeamID) REFERENCES Teams(ID);
END;

CREATE OR ALTER PROCEDURE RemoveFK 
AS
BEGIN
ALTER TABLE Fans
DROP CONSTRAINT fk_Fans_Teams;
END;